---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus-blackbox-exporter
  namespace: observability
spec:
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: '>=8.12.0 <9.0.0'
  interval: 1h0m0s
  timeout: 10m
  install:
    remediation:
      retries: 3
    crds: Create
  upgrade:
    remediation:
      retries: 3
    crds: CreateReplace
  values:
    extraArgs:
      - --log.level=debug
    tolerations:
      - key: node-role.kubernetes.io/master   # we put observability stack on controlplane nodes to utilize their resources
        operator: Exists
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
    pspEnabled: false
    config:
      modules:
        http_2xx:
          prober: http
          timeout: 5s
          http:
            valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
            follow_redirects: true
            preferred_ip_protocol: "ip4"
        http_2xx_insecure:
          prober: http
          timeout: 5s
          http:
            valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
            follow_redirects: true
            preferred_ip_protocol: "ip4"
            tls_config:
              insecure_skip_verify: true
        dns_external:
          prober: dns
          timeout: 5s
          dns:
            transport_protocol: "udp"
            preferred_ip_protocol: "ip4"
            query_name: "www.google.com"
            query_type: "A"
            valid_rcodes:
              - NOERROR
