apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - namespace.yaml
  - netpol.yaml
  - alerts
  - goldpinger.yaml
  - loki.yaml
  - kube-prometheus-stack.yaml
  - blackbox-exporter.yaml
  - victoriametrics.yaml