apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - namespace.yaml
  - netpol.yaml
  - alerts
  - victoriametrics.yaml
  - kube-prometheus-stack.yaml
  # - loki.yaml   # loki values should be adjusted to get enabled
