---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: default-namespace-network-policies
spec:
  chart:
    spec:
      chart: ./charts/security/default-namespace-network-policies
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 1h0m0s
  releaseName: default-namespace-network-policies
  timeout: 10m
  install:
    remediation:
      retries: 3
    crds: Create
  upgrade:
    remediation:
      retries: 3
    crds: CreateReplace
  values:
    allow_namespace_traffic: true
    allow_ingress_cluster_traffic: true
    allow_egress_cluster_traffic: true
    allow_ingress_private_traffic: true
    allow_egress_private_traffic: true
    allow_monitoring: true
    allow_apiserver: true
    allow_internet: false
    allow_ingress_traffic: true
    allow_egress_traffic: false

# Allow Grafana to contact external servers (plugins, auth, etc.)
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-grafana
spec:
  egress:
  - ports:
    - port: 443
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: grafana
  policyTypes:
  - Egress

# Allow Alertmanager to contact external servers (slack)
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-alertmanager
spec:
  egress:
  - ports:
    - port: 443
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: alertmanager
  policyTypes:
  - Egress

# Allow Blackbox Exporter to probe external URLs.
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-blackbox-exporter
spec:
  egress:
  - ports:
    - port: 443
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: prometheus-blackbox-exporter
  policyTypes:
  - Egress