---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: victoriametrics
  namespace: observability
spec:
  chart:
    spec:
      chart: victoria-metrics-single
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: flux-system
      version: '0.8.0'
  interval: 1h0m0s
  timeout: 10m
  install:
    remediation:
      retries: 3
    crds: Create
  upgrade:
    remediation:
      retries: 3
    crds: CreateReplace
  values:
    server:
      fullnameOverride: victoriametrics
      retentionPeriod: 12