apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - kubernetes.yaml
  - flux.yaml
  - loki.yaml
  - minio.yaml
  - mongodb.yaml
  - nginx.yaml
  - node.yaml
  # - redis.yaml   # commented as redis cluster got shut down, uncomment when it is back up
  - probes.yaml