---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: http-endpoint-alerts
spec:
  groups:
  - name: http-probe-rules
    rules:
    - alert: ProbeFailing
      expr: probe_success == 0
      for: 15m
      labels:
        severity: high
      annotations:
        summary: Endpoint Down
        description: "Endpoint is Down: {{ $labels.instance }}"