apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: awesome-prometheus-rules-vault
spec:
  groups:
    - name: vault.rules
      rules:
        - alert: VaultSealed
          expr: vault_core_unsealed == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: Vault sealed (instance {{ $labels.instance }})
            description: "Vault instance is sealed on {{ $labels.instance }}\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
        - alert: VaultTooManyPendingTokens
          expr: avg by (namespace, pod, container) (vault_token_create_count -  vault_token_store_count) > 50
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: Vault too many pending tokens (instance {{ $labels.instance }})
            description: "Too many pending tokens {{ $labels.instance }}: {{ $value | printf \"%.2f\"}}%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
        - alert: VaultTooManyInfinityTokens
          expr: vault_token_count_by_ttl{creation_ttl="+Inf"} > 50
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: Vault too many infinity tokens (instance {{ $labels.instance }})
            description: "Too many infinity tokens {{ $labels.instance }}: {{ $value | printf \"%.2f\"}}%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
        - alert: VaultClusterHealth
          expr: vault_core_active{cluster=~"vault-.*"} < 1
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: Vault cluster is unstable
            description: "Vault cluster is not healthy {{ $labels.instance }}: {{ $value | printf \"%.2f\"}}%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
        - alert: VaultAutopilotNodeHealthy
          # Set to 1 if Autopilot considers all nodes healthy
          # https://www.vaultproject.io/docs/internals/telemetry#integrated-storage-raft-autopilot
          expr: vault_autopilot_healthy < 1
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: Autopilot Vault Raft node unhealthy
            description: At least one of the Autopilot Vault Raft nodes is unhealthy
        - alert: VaultLeadershipLoss
          expr: sum(increase(vault_core_leadership_lost_count[1h])) > 5
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: High frequency of Vault leadership losses
            description: There have been more than 5 Vault leadership losses in the past 1h
        - alert: VaultRequestFailures
          expr: increase(vault_audit_log_request_failure[5m]) > 0
          for: 15m
          labels:
            severity: critical
          annotations:
            summary: High frequency of failed Vault requests
            description: There has been an increased number of failed Vault requests in the last 15 minutes
        - alert: VaultResponseFailures
          expr: increase(vault_audit_log_response_failure[5m]) > 0
          for: 15m
          labels:
            severity: critical
          annotations:
            summary: High frequency of failed Vault responses
            description: There has been an increased number of failed Vault responses in the last 15 minutes
