apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      version: ">=4.0.0 <5.0.0"
  interval: 1h0m0s
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  # Default values
  # https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
  values:
    controller:
      kind: DaemonSet
      hostPort:
        enabled: true
      service:
        type: ClusterIP
      ingressClassResource:
        name: nginx-dev
        default: false
        controllerValue: "k8s.io/ingress-nginx-dev"
      ingressClassByName: true
      ingressClass: nginx-dev   # backwards compatibility
      config:
        enable-real-ip: "true"   # to reveal source ip properly
        forwarded-for-header: proxy_protocol   # to reveal source ip properly
        # modsecurity
        enable-modsecurity: "false"
        enable-owasp-modsecurity-crs: "false"
        http-snippet: |
          proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=static-cache:10m max_size=30g inactive=24h use_temp_path=off;
        modsecurity-snippet: |
          # Increment this to force nginx to reload the rules when you change the configmap: 1.0.1
          Include /etc/nginx/owasp-modsecurity-crs/custom/custom-modsecurity.conf
      extraArgs:
        enable-ssl-passthrough: true
      allowSnippetAnnotations: true
      admissionWebhooks:
        enabled: false
      # this block is for modsecurity
      extraVolumeMounts:
        - name: modsecurity-config
          mountPath: /etc/nginx/owasp-modsecurity-crs/custom/
      extraVolumes:
        - name: modsecurity-config
          configMap:
            name: modsecurity-config
      nodeSelector:
        dedicated: prod
      tolerations:
      - key: dedicated
        operator: Equal
        value: prod
    defaultBackend:
      enabled: true
      tolerations:
      - key: dedicated
        operator: Equal
        value: prod