---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: default-namespace-network-policies
spec:
  chart:
    spec:
      chart: ./helm/charts/security/default-namespace-network-policies
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 1h0m0s
  releaseName: default-namespace-network-policies
  timeout: 10m
  install:
    remediation:
      retries: 3
    crds: Create
  upgrade:
    remediation:
      retries: 3
    crds: CreateReplace
  values:
    allow_namespace_traffic: false
    allow_ingress_cluster_traffic: true
    allow_egress_cluster_traffic: true
    allow_ingress_private_traffic: false
    allow_egress_private_traffic: false
    allow_monitoring: true
    allow_apiserver: true
    allow_internet: false
    allow_ingress_traffic: true
    allow_egress_traffic: false

# Allow Falco to contact external servers (fetching kernel falco modules)
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-falco
spec:
  egress:
  - ports:
    - port: 443
      protocol: TCP
    - port: 45000   # falco k8s meta collector
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: falco
  policyTypes:
  - Egress

# Allow Kyverno to contact external servers (attesting ghcr images)
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-kyverno
spec:
  egress:
  - ports:
    - port: 443
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/component: admission-controller
      app.kubernetes.io/instance: kyverno
  policyTypes:
  - Egress
