resources:
- ../base

nameSuffix: -meet

commonLabels:
  app: demoapp-data-processor-meet

images:
- name: demoapp-data-processor
  newName: nginxinc/nginx-unprivileged

configMapGenerator:
- name: demoapp-data-processor
  behavior: merge
  literals:
  - APP_NAME='demoapp-data-processor-meet'

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/name
      value: demoapp-data-processor-meet
  target:
    kind: Deployment
- patch: |-
    - op: add
      path: "/metadata/labels/type"
      value: group
  target:
    kind: Deployment 
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: 250m
          memory: 512Mi
  target:
    kind: Deployment