apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: local-path-storage
resources:
  - local-path-storage.yaml
  - netpol.yaml
patchesStrategicMerge:
  - local-path-storage-patch.yaml
