apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- pdb.yaml
- hpa.yaml
- servicemonitor.yaml
commonLabels:
  group: demoapp-home
configMapGenerator:
- name: demoapp-home
  literals:
  - PORT='8080'