{{- if .Values.allow_egress_cluster_traffic }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  labels:
    {{- include "default-namespace-network-policies.labels" . | nindent 4 }}
  name: allow-egress-from-all-to-cluster
spec:
  policyTypes:
  - Egress
  podSelector: {}
  egress:
  - to:
    - namespaceSelector: {}
{{- end }}
