{{- if .Values.allow_internet }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  labels:
    {{- include "default-namespace-network-policies.labels" . | nindent 4 }}
  name: allow-egress-internet
spec:
  policyTypes:
  - Egress
  podSelector: {}
  egress:
  - ports:
    - port: 80
      protocol: TCP
    - port: 443
      protocol: TCP
{{- end }}
