{{- if .Values.allow_ingress_private_traffic }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  labels:
    {{- include "default-namespace-network-policies.labels" . | nindent 4 }}
  name: allow-ingress-from-private-network-to-all
spec:
  policyTypes:
  - Ingress
  podSelector: {}
  ingress:
  # RFC 1918
  - from:
    - ipBlock:
        cidr: 10.0.0.0/8
    - ipBlock:
        cidr: 172.16.0.0/12
    - ipBlock:
        cidr: 192.168.0.0/16
{{- end }}
