{{- if .Values.allow_egress_traffic }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-egress
  labels:
    {{- include "default-namespace-network-policies.labels" . | nindent 4 }}
spec:
  podSelector: {}
  egress:
  - {}
  policyTypes:
  - Egress
{{- end }}
