apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kubernetes-api-ingress.yaml
  - rbac
  - flux-system
  - infra/flux-ks.yaml
  - apps/demoapp-home/flux-ks.yaml
  - apps/demoapp-work/flux-ks.yaml
  - apps/demoapp-work/flux-ks-feature3.yaml
