---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demoapp-home-dev
  namespace: flux-system
spec:
  dependsOn:
    - name: operations
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/demo-000/apps/demoapp-home/dev
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demoapp-home-stg
  namespace: flux-system
spec:
  dependsOn:
    - name: operations
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/demo-000/apps/demoapp-home/stg
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demoapp-home-prod
  namespace: flux-system
spec:
  dependsOn:
    - name: operations
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/demo-000/apps/demoapp-home/prod
  prune: true
