---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: demoapp-auth
    group: demoapp-auth
  name: demoapp-auth
spec:
  endpoints:
  - port: http
    path: /healthz
  selector:
    matchLabels:
      app: demoapp-auth
