--- 
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demoapp-work-feature2
  namespace: flux-system
spec:
  interval: 60m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/demo-000/apps/demoapp-work/feature2
  prune: true

