---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demoapp-data-processor-dev
  namespace: flux-system
spec:
  dependsOn:
    - name: operations
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/demo-000/apps/demoapp-data-processor/dev
  prune: true
