---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demoapp-auth-dev
  namespace: flux-system
spec:
  dependsOn:
    - name: operations
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/demo-000/apps/demoapp-auth/dev
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demoapp-auth-stg
  namespace: flux-system
spec:
  dependsOn:
    - name: operations
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/demo-000/apps/demoapp-auth/stg
  prune: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demoapp-auth-prod
  namespace: flux-system
spec:
  dependsOn:
    - name: operations
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/demo-000/apps/demoapp-auth/prod
  prune: true
