apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demoapp-work-dev
resources:
  - namespace.yaml
  - ../../../../../apps/demoapp-work
images:
  - name: nginxinc/nginx-unprivileged
    newTag: '1.22'
configMapGenerator:
  - name: demoapp-work-call
    behavior: merge
    literals:
      - BASE_URL="https://dev.movie.demoapp-work.example.com"
      - MEET_URL="http://demoapp-work-meet"
      - SOLVE_URL="http://demoapp-work-solve"
  - name: demoapp-work-meet
    behavior: merge
    literals:
      - SOLVE_URL="http://demoapp-work-solve"
  - name: demoapp-work-solve
    behavior: merge
    literals:
      - MEET_URL="http://demoapp-work-meet"
      - TIMEOUT="60"
patches:
  # No need for autoscaling on dev
  - patch: |-
      $patch: delete
      apiVersion: autoscaling/v1
      kind: HorizontalPodAutoscaler
      metadata:
        name: any
    target:
      kind: HorizontalPodAutoscaler
      labelSelector: group=demoapp-work
  # No need for resource restrictions on dev
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value: {}
    target:
      kind: Deployment
      labelSelector: group=demoapp-work
  # Add tolerations
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: any
      spec:
        template:
          spec:
            tolerations:
            - key: dedicated
              operator: Equal
              value: dev
    target:
      kind: Deployment
      labelSelector: group=demoapp-work
  # Add variable indicating environment
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: ENVIRONMENT
          value: dev
    target:
      kind: Deployment
      labelSelector: group=demoapp-work
