apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
- netpol.yaml
- gotk-components.yaml
- gotk-sync.yaml
# - pod-monitor.yaml   # here we have a chicken-egg problem, pod-monitor should be added only after kube-prometheus-stack deployment
