apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- pdb.yaml
- servicemonitor.yaml
commonLabels:
  group: demoapp-data-processor
configMapGenerator:
- name: demoapp-data-processor
  literals:
  - PORT='8080'