---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: demoapp-data-processor
    group: demoapp-data-processor
  name: demoapp-data-processor
spec:
  endpoints:
  - port: http
    path: /healthz
  selector:
    matchLabels:
      app: demoapp-data-processor
