apiVersion: v1
kind: Service
metadata:
  name: demoapp-data-processor
spec:
  selector:
    group: demoapp-data-processor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
