---
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha2"
    kind: "DeschedulerPolicy"
    profiles:
      - name: Default
        pluginConfig:
        - name: "DefaultEvictor"
          args:
            evictLocalStoragePods: true
        - name: "RemovePodsViolatingInterPodAntiAffinity"
        - name: "RemovePodsViolatingNodeTaints"
        - name: "RemoveDuplicates"
        - name: "LowNodeUtilization"
          args:
            thresholds:
              "cpu" : 20
              "memory": 20
              "pods": 20
            targetThresholds:
              "cpu" : 75
              "memory": 75
              "pods": 75
        plugins:
          balance:
            enabled:
              - "LowNodeUtilization"
              - "RemoveDuplicates"
          deschedule:
            enabled:
              - "RemovePodsViolatingInterPodAntiAffinity"
              - "RemovePodsViolatingNodeTaints"
