---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
spec:
  values:
    extraArgs:
      config.expand-env: true
    tolerations:
      - key: node-role.kubernetes.io/master   # we put observability stack on controlplane nodes to utilize their resources
        operator: Exists
