
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: app-probes
  namespace: observability
spec:
  module: http_2xx
  prober:
    url: prometheus-blackbox-exporter:9115
  targets:
    staticConfig:
      labels:
        cluster: demo-000
      static:
      - https://grafana-001.example.com/healthz

---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: k8s-api-probe
  namespace: observability
spec:
  module: http_2xx_insecure
  prober:
    url: prometheus-blackbox-exporter:9115
  targets:
    staticConfig:
      labels:
        cluster: demo-000
      static:
      - https://k8s-api-001.example.com/healthz
