apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - ../../../../infra/observability
  - secrets.yaml

patches:
  - path: victoriametrics.patch.yaml
    target:
      kind: HelmRelease
      name: victoriametrics
  - path: kube-prometheus-stack.patch.yaml
    target:
      kind: HelmRelease
      name: kube-prometheus-stack
  - path: blackbox-exporter.patch.yaml
    target:
      kind: HelmRelease
      name: blackbox-exporter
  - path: loki.patch.yaml
    target:
      kind: HelmRelease
      name: loki
