apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - netpol-default.yaml
  - descheduler
  - sealed-secrets
  - kubelet-csr-approver.yaml
  - reflector.yaml
  - secret-generator.yaml
  - etcd-defrag.yaml
  - eventrouter.yaml
