---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: secret-generator
  namespace: kube-system
spec:
  chart:
    spec:
      chart: kubernetes-secret-generator
      sourceRef:
        kind: HelmRepository
        name: mittwald
        namespace: flux-system
      version: '>=3.4.0 <4.0.0'
  interval: 1h0m0s
  releaseName: secret-generator
  timeout: 60m
  install:
    remediation:
      retries: 3
    crds: Create
  upgrade:
    remediation:
      retries: 3
    crds: CreateReplace
  values:
    fullnameOverride: secret-generator
    tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
    podSecurityContext:
      fsGroup: 2000
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault