name: Flux - validate repository manifests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup tools
        uses: fluxcd/flux2-kustomize-helm-example/.github/actions/tools@main
      - name: Validate manifests
        working-directory: ./clusters
        run: |
          wget https://raw.githubusercontent.com/fluxcd/flux2-kustomize-helm-example/main/scripts/validate.sh
          for dir in apps clusters infra
          do 
            cd $dir
            bash ../validate.sh
            cd -
          done