name: Bring down demo env

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

jobs:
  demo-env-delete:
    if: startsWith(github.event.label.*.name, 'deploy-')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout Flux repo
        uses: actions/checkout@master
        with:
          ref: main
          repository: ${{ github.repository_owner }}/flux2-general
          token: ${{ secrets.TOKEN_RW }}

      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.6

      - name: Dump github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Extract feature name
        id: feature_name
        env:
          LABELS: ${{ steps.pr-labels.outputs.labels }}
        run: |
          echo $LABELS
          LABEL1=$(echo $LABELS | grep -o -E "deploy-[a-zA-Z0-9]*" | sed "s|deploy-||")
          printenv | grep GITHUB_PR_LABEL_DEPLOY
          LABEL2=$(printenv | grep GITHUB_PR_LABEL_DEPLOY | sed "s|DEPLOY_||")
          echo "LABEL1 is $LABEL1 and LABEL2 is $LABEL2"
          echo "feature_name=$LABEL1" >> $GITHUB_OUTPUT

      - name: Clean up
        env:
          NAME: ${{ steps.feature_name.outputs.feature_name }}
        run: |
          git checkout tags/deploy-${NAME}
          git revert HEAD --no-edit
          git status
          git push origin main
          git tag -d ${NAME}
          git push --delete origin ${NAME}

      - uses: actions/github-script@v3
        env:
          NAME: ${{ steps.feature_name.outputs.feature_name }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${{env.NAME}} namespace has been deleted`
            })