apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - bitnami.yaml
  - ingress-nginx.yaml
  - sealed-secrets.yaml
  - jetstack.yaml
  - prometheus-community.yaml
  - grafana.yaml
  - victoriametrics.yaml
  - teleport.yaml
  - falco.yaml
  - kubelet-csr-approver.yaml
  - kyverno.yaml
  - emberstack.yaml